language: python
sudo: false
branches:
  only:
  - master
env:
  global:
    secure: "wfwHw9oDC/Xhu1Kguk00Ht2obfbIaTtElliFvTCV74Dnc5vWW54l0TKj0oMH8WP1nNI9aiiG+cWaDaAYjkLzL3ILSfbKSF06LtFiZMsQPDAmQYq2pl35RMyNQkX+/j2Nd7efCN3BwhRtQYfngrKJIpZms5O0t1f4mTf6Yn4j8akgsmeWVDB12wSDhsxqsY5fjhH3gESv9VjBAs4FiX5FKvaPGK5B1/nwmB+AZKRY1gl4CJ25P2ZQ0wq6Cb/pK0J58ciZJqYt4CkJpvYDBG4cTINiOObiFZldvw2JdiWel0fRXayFHoyY15RGGU70zX148cVlyG/A6u/KsE4yVf2HRZtrB8M5oEuwLXHGCD3abD5QM1b1MABIvEPr+eSXTPp+b17XOCf5uXr4E9nEe3MyoSUdaGJk398felMnFY4ITcWoPfuKm61PodxUwMNSv6Y1cZqBKW5Hged9CWihPPw535P+qcpSCrZhOOabUljI1xlLmTp4EzFNJOp8aIBF5sJ+LTdpmhdONk3RQf07c52A0jylYukvPWDg5iYpYWG7iQkoTwmcUO9xX+If7M4dVnXPL8+YiZjqJzEIui9Dc1DPK2ZrZJc9FMfdu+VasNRyJ/TZkrf+Mtq6u15Kqtqns3kLLM5b9/LprLS/XINvCe4ZrKhSENUMA0hOzi0GILWp3ZU="

install:
  - pip install hererocks
  - hererocks env -l5.3 -rlatest
  - source env/bin/activate
  - luarocks install ldoc

before_script:
  - |

    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Decrypt the file containing the private key

    openssl aes-256-cbc \
      -K $encrypted_0ca435473fa8_key \
      -iv $encrypted_0ca435473fa8_iv \
      -in ".travis/gh-pages.enc" \
      -out "$SSH_FILE" -d

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Enable SSH authentication

    chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
        "Host github.com" \
        "  IdentityFile $SSH_FILE" \
        "  LogLevel ERROR" >> ~/.ssh/config

script:
  - |

    set -o errexit -o nounset

    declare -r GH_PAGES_SOURCES="Makefile config.ld script/"
    cd $TRAVIS_BUILD_DIR

    git config --global user.name $GH_USER_NAME
    git config --global user.email $GH_USER_EMAIL

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Fetch and checkout gh-pages branch
    git remote set-branches --add origin gh-pages
    git fetch
    git checkout gh-pages

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Check out just the bits we need to generate docs from master
    git checkout master $GH_PAGES_SOURCES
    git reset HEAD

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Build docs
    make docs

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Remove previous doc folders
    rm -rf modules scripts

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # And move new folders into place
    mv -fv docs/* ./

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Remove build artifacts so they don't get checked in
    rm -rf $GH_PAGES_SOURCES docs env

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Add new docs, commit and push to origin
    git add -A
    git commit -m "Generated gh-pages for `git log master -1 --pretty=short --abbrev-commit`"
    git push upstream gh-pages
    git checkout --force master
